/teleop:
  ros__parameters:
    frequency: 100  # set to 0, to disable manual flight modes
    mode: "high_level" # one of none, cmd_rpy, cmd_vel_world
    cmd_rpy:
      roll:
        axis: 1
        scale: 1.0
        max: 30.0 # deg
        deadband: 0.0
      pitch:
        axis: 2
        scale: 1.0
        max: 30.0 # deg
        deadband: 0.0
      yawrate:
        axis: 3
        scale: 1.0
        max: 200.0 # deg/s
        deadband: 5.0 # deg/s
      thrust:
        axis: 4
        scale: 1.0
        max: 60000.0 # PWM
        deadband: 0.0
    cmd_vel_world:
      x_velocity:
        axis: 2
        scale: 1.0
        max: 0.5 # m/s
        deadband: 0.1 # m/s
      y_velocity:
        axis: 1
        scale: 1.0
        max: 0.5 # m/s
        deadband: 0.1 # m/s
      z_velocity:
        axis: 4
        scale: 1.0
        max: 0.5 # m/s
        deadband: 0.1 # m/s
      yaw_velocity:
        axis: 3
        scale: 1.0
        max: 0.5 # rad/s
        deadband: 0.1 # rad/s
      # workspace limits
      x_limit: [-2.0, 2.0] # m
      y_limit: [-2.0, 2.0] # m
      z_limit: [0.0, 2.5] # m
    initial_position:
      x: 0.0
      y: 0.0
      z: 0.10
    auto_yaw_rate: 0.0 # rad/s, use 0.0 for manual yaw control
    takeoff:
      duration: 2.0
      height: 1.5
      button: 10  # R1
    land:
      button: 9 # L1
    emergency:
      button: 2 # square 
    arm:
      button: 3 # triangle
    control:
      button: 1 # circle

